/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** status + version for load balancers */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/flags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** feature flags for the caller (sticky canary bucket cookie) */
    get: operations["getFlags"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** access code -> session cookie. rate limited, JSON only */
    post: operations["openSession"];
    delete: operations["closeSession"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** my CV as json (profile:read) */
    get: operations["getProfile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/contact": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** phone + whatsapp (contact:read, recruiter or admin) */
    get: operations["getContact"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** recent access decisions (audit:read, admin only) */
    get: operations["getAudit"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pokemon": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listPokemon"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pokemon/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPokemon"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/moves/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getMove"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/route": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** shortest round trip through the kanto gyms */
    get: operations["planGymTour"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/coach": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** AI coach. streams server-sent events (delta, fallback, diagnosis, error, done) */
    post: operations["coachTeam"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/hire": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** the HIRE button. fans out to slack + a signed webhook */
    post: operations["hireClicked"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    Role: "visitor" | "recruiter" | "admin";
    /** @enum {string} */
    Permission: "profile:read" | "pokedex:read" | "coach:use" | "contact:read" | "audit:read";
    Error: {
      error: string;
      requestId?: string;
    };
    Forbidden: {
      /** @constant */
      error: "forbidden";
      need: components["schemas"]["Permission"];
      youAre: components["schemas"]["Role"];
    };
    Health: {
      /** @constant */
      status: "ok";
      version: string;
      uptimeS: number;
    };
    Flags: {
      "smart-ai": boolean;
      "shiny-sprites": boolean;
    };
    Me: {
      role: components["schemas"]["Role"];
      permissions: components["schemas"]["Permission"][];
      expiresAt: number | null;
    };
    Contact: {
      email: string;
      phone: string | null;
      whatsapp: string | null;
    };
    AuditEntry: {
      at: number;
      role: components["schemas"]["Role"];
      action: string;
      allowed: boolean;
    };
    PokemonSummary: {
      id: number;
      name: string;
      sprite: string;
    };
    BaseStats: {
      hp: number;
      attack: number;
      defense: number;
      specialAttack: number;
      specialDefense: number;
      speed: number;
    };
    Move: {
      name: string;
      type: string;
      power: number | null;
    };
    PokemonDetails: components["schemas"]["PokemonSummary"] & {
      types: string[];
      heightM: number;
      weightKg: number;
      abilities: {
        name: string;
        hidden: boolean;
      }[];
      stats: components["schemas"]["BaseStats"];
      moveNames: string[];
      description: string;
      evolutions: components["schemas"]["PokemonSummary"][];
    };
    TeamMember: {
      id: number;
      name: string;
      sprite: string;
      types: string[];
      stats: components["schemas"]["BaseStats"];
      moves: components["schemas"]["Move"][];
    };
    Stop: {
      id: string;
      name: string;
      x: number;
      y: number;
    };
    Tour: {
      order: components["schemas"]["Stop"][];
      distance: number;
    };
  };
  responses: {
    /** @description error */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description your role doesn't have the permission */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Forbidden"];
      };
    };
  };
  parameters: {
    Slug: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  getFlags: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description flag values */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Flags"];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description your role + permissions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  openSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          accessCode: string;
        };
      };
    };
    responses: {
      /** @description session opened, Set-Cookie hm_session */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      400: components["responses"]["Error"];
      401: components["responses"]["Error"];
      415: components["responses"]["Error"];
      429: components["responses"]["Error"];
    };
  };
  closeSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description cookie dropped */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            ok: boolean;
          };
        };
      };
    };
  };
  getProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  getContact: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description contact */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Contact"];
        };
      };
      403: components["responses"]["Forbidden"];
    };
  };
  getAudit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description newest first */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditEntry"][];
        };
      };
      403: components["responses"]["Forbidden"];
    };
  };
  listPokemon: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description gen 1 list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokemonSummary"][];
        };
      };
      502: components["responses"]["Error"];
    };
  };
  getPokemon: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: components["parameters"]["Slug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description full entry */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokemonDetails"];
        };
      };
      404: components["responses"]["Error"];
      502: components["responses"]["Error"];
    };
  };
  getMove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: components["parameters"]["Slug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description move */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Move"];
        };
      };
      404: components["responses"]["Error"];
    };
  };
  planGymTour: {
    parameters: {
      query?: {
        from?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description tour */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Tour"];
        };
      };
      404: components["responses"]["Error"];
    };
  };
  coachTeam: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          team: components["schemas"]["TeamMember"][];
          log?: {
            [key: string]: unknown;
          }[];
        };
      };
    };
    responses: {
      /** @description text/event-stream. the `diagnosis` event carries a Diagnosis + the model that answered */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": string;
        };
      };
      400: components["responses"]["Error"];
      429: components["responses"]["Error"];
    };
  };
  hireClicked: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            ok: boolean;
          };
        };
      };
      429: components["responses"]["Error"];
    };
  };
}
